#!/bin/bash
#        __                  .__
#       |  | _______    _____|__| ______
#       |  |/ /\__  \  /  ___/  |/  ___/
#       |    <  / __ \_\___ \|  |\___ \
#       |__|_ \(____  /____  >__/____  >
#            \/     \/     \/        \/
# --------------------------------------------- #
# Kritiqual's Arch linux Setup & Install Script #
#      (Basically it's a fork of archfi)        #
# --------------------------------------------- #
# > Author: Kritiqual
# > License:
#     >> https://www.gnu.org/licenses/gpl-3.0.html
#
# > References:
#     >> Arch linux installation guide:
#           https://wiki.archlinux.org/title/Installation_guide
#
#     >> Archfi:
#           https://github.com/MatMoul/archfi
#           http://sourceforge.net/projects/archfi/
#
#     >> Arch linux Installation Framework:
#           https://github.com/jdodds/aif

### Define some variables ###
NAME="Kritiqual's Arch linux Setup & Install Script"
VER="kasis v.A-01"

### Preps menu ###
menu() {
    menu_opts=()
    menu_opts+=("About" "About kasis")
    menu_opts+=("Set keyboard layout" "")
    menu_opts+=("Choose Editor" "(vim, nano, ...)")
    menu_opts+=("Reboot" "Reboot the system")

    chosen=$(whiptail --backtitle "$NAME - $VER" --title "Installation menu" \
        --menu "  Tips: TAB to opt out of menu lists" 0 0 0 "${menu_opts[@]}" \
        --default-item "Set keyboard layout" 3>&1 1>&2 2>&3)

    case ${chosen} in
    "About") about ;;
    "Set keyboard layout") kbmenu ;;
    "Choose Editor") editormenu ;;
    "Reboot") rebootmenu ;;
    esac
}

#--- about ---#
about() {
    whiptail --backtitle "$NAME - $VER" --title "About kasis" \
        --msgbox "Kritiqual's Arch linux Setup & Install Script\nis a script created by Kritiqual used to setup\nArch linux from fresh install and download more package afterward (optional)\n\nIt aims to make the process easier to both beginner and experienced users" \
        13 50
}

#--- kbmenu ---#
kbmenu() {
    kblists=()
    for kb in $(ls -R /usr/share/kbd/keymaps | grep "map.gz" | sed 's/\.map\.gz//g' | sort); do
        kblists+=("${kb}" "")
    done

    chosen=$(whiptail --backtitle "$NAME - $VER" --title "Choose your keyboard" \
        --menu "  Tips: TAB to opt out of menu lists" 0 0 0 "${kblists[@]}" \
        --default-item "us" 3>&1 1>&2 2>&3)

    if [ "$?" = "0" ]; then
        loadkeys ${chosen} &
        whiptail --backtitle "$NAME - $VER" --title "Change keyboard" \
            --msgbox "Loaded key ${chosen}" 0 0
    fi
}

#--- editormenu ---#
editormenu() {
    editorlists=()
    editorlists+=("Nano" "(Default)")
    editorlists+=("Vim" "")

    chosen=$(whiptail --backtitle "$NAME - $VER" --title "Choose your editor" \
        --menu "  Tips: TAB to opt out of menu lists" 0 0 0 "${editorlists[@]}" \
        --default-item "Default" 3>&1 1>&2 2>&3)

    if [ "$?" = "0" ]; then
        export EDITOR=${chosen}
        whiptail --backtitle "$NAME - $VER" --title "Change keyboard" \
            --msgbox "export EDITOR=${chosen}" 0 0
    fi
}

#--- rebootmenu ---#
rebootmenu() {
    if (whiptail --backtitle "$NAME - $VER" --title "Reboot" --yesno "Reboot system now?" 0 0 --defaultno); then
        clear
        reboot
    fi
}


while true; do
    menu
done
